apiVersion: v1
kind: Namespace
metadata:
  name: nicolasHernandezS 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tuinicialyapellido
data:
  USER_KEY: "mi-usuario-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tuinicialyapellido
type: Opaque
stringData:
  BD_PASSWORD: "super-password-secreto"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  namespace: tuinicialyapellido
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: ghcr.io/tu-usuario-github/curso-devops-lab3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: USER_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_KEY
        - name: BD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: BD_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
  namespace: tuinicialyapellido
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nestjs-app